# Base Image
FROM python:3.11-slim-bullseye

# pip install requirements
RUN pip install --upgrade pip
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# COPY app
COPY ./app /app

CMD uvicorn main:feast --host 0.0.0.0 --port 22124 --app-dir /app
